<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>WatchList.Presentation</RootNamespace>
    <UserSecretsId>aspnet-WatchList-be8fb7ac-113c-4648-9cef-867a93b91410</UserSecretsId>
    <RequiresAspNetWebAssets>true</RequiresAspNetWebAssets>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WatchList.Application\WatchList.Application.csproj" />
    <ProjectReference Include="..\WatchList.Infrastructure\WatchList.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="AppData\**" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
